# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Alarm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(True)
        mainWindow.resize(292, 44)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMaximumSize(QtCore.QSize(292, 44))
        mainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        mainWindow.setAutoFillBackground(False)
        mainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setStyleSheet(
            "border-color: rgb(85, 255, 255);\n""background-color: rgb(0, 153, 153);"
        )
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.alarmEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.alarmEdit.setStyleSheet(
            "font: 12pt \"MS Shell Dlg 2\";\n""background-color: rgb(255, 170, 0);")
        self.alarmEdit.setObjectName("alarmEdit")
        self.horizontalLayout.addWidget(self.alarmEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setStyleSheet(
            "font: 10pt \"MS Shell Dlg 2\";\n""background-color: rgb(255, 7, 0);\n""\n""\n"""
        )
        self.pushButton.setShortcut("")
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.radioButton.setCheckable(True)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Alarm"))
        mainWindow.setToolTip(_translate(
            "mainWindow",
            "<html><head/><body><p align=\"center\"><br/></p></body></html>")
        )
        self.alarmEdit.setDisplayFormat(_translate("mainWindow", "HH:mm"))
        self.pushButton.setText(_translate("mainWindow", "SET / STOP"))
        self.radioButton.setText(_translate("mainWindow", "Turn off at 20:00"))
